### ISSUE TITLE
Stateless rules in firewall_policy.tf incorrect?

### ISSUE THREAD

**Issue by paulgear** [aws-samples/manage-aws-network-firewall-multi-account-aws-firewall-manager#1]
Hi, thanks for providing this resource.

I'm just looking at the [stateless rules to drop remote traffic](https://github.com/aws-samples/manage-aws-network-firewall-multi-account-aws-firewall-manager/blob/main/firewall_policy.tf#L33) and it seems like the ssh rule won't match the correct traffic. (I haven't implemented a firewall based on this code yet, so I haven't empirically verified this.)

https://docs.aws.amazon.com/network-firewall/latest/developerguide/stateless-rule-groups-standard.html says (emphasis mine):

> Match settings
> 
> A stateless rule has the following match settings. These specify what the Network Firewall stateless rules engine looks for in a packet. To be a match, a packet must satisfy **all** of the match settings in the rule.

The [ssh drop rule](https://github.com/aws-samples/manage-aws-network-firewall-multi-account-aws-firewall-manager/blob/main/firewall_policy.tf#L43) is setting both source and destination port to 22, which will not match traffic for any ssh implementations I've used (they use an ephemeral source port).  Therefore it seems this rule needs to be split into two (one for source matches, and one for destination matches) in order to achieve its aims.

If I'm missing something, please let me know.  Otherwise, I'm happy to test and contribute a patch for this.

**Comment by paulgear** [comment]
Also, if the intent is to drop remote access ports, then it seems the second rule should be dropping Remote Desktop Protocol (TCP/UDP port 3389) rather than Reliable Datagram Protocol (proto 27).

**Comment by pablo19sc** [comment]
Hi @paulgear thanks for your feedback! 100% true, I updated the ports for the SSH traffic. Also true the RDP feedback, what I did in the last update was to remove that part as we don't have Windows machines.

Note that I refactor the code to have a dedicated folder for each AWS Account. So now the firewall configuration is in central_account/firewall_policy.tf
